apiVersion: apps/v1
kind: Deployment
metadata:
  name: convertor-deployment
  labels:
    app: convertor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: convertor
  template:
    metadata:
      labels:
        app: convertor
    spec:
      containers:
        - name: convertor
          image: joeyhd/temp_convertor
          ports:
            - containerPort: 5001
---